apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
    app: jenkins
  annotations:
    volume.alpha.kubernetes.io/storage-class: jenkins-storage
spec:
  volumeMode: Filesystem
  storageClassName: jenkins-storage
#  persistentVolumeReclaimPolicy: Delete - deletes all storage if claim is removed
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/kubestorage/jenkins"
    server: 10.0.0.14
